### ISSUE TITLE
Enhance ranking logic to prioritize contributors with more Pull Requests

### ISSUE THREAD

**Issue by sabhisharma-ise** [girlscript/gssoc22-leaderboard-backend#3]
First of all, I want to express my appreciation for the GSSOC'23 leaderboard-backend repository. It has been an amazing experience participating in GSSOC and witnessing the incredible contributions from all the talented developers involved. Kudos to the entire team!

I noticed that in cases where two or more contributors have the same score, the current ranking logic doesn't take into account the number of Pull Requests submitted by each contributor. This can sometimes result in a less accurate representation of the overall contributions made by participants. See the screenshot below:-

![image](https://github.com/girlscript/gssoc22-leaderboard-backend/assets/100849696/3c6791b3-1707-45d1-995b-12b115b73876)

Expected Behavior:
When two or more contributors have the same score, the algorithm should compare the number of Pull Requests submitted by each contributor. The contributor with a higher number of Pull Requests should be ranked higher than the others with an equal score.

Hope the team will take into consideration of this suggestion!

**Comment by sabhisharma-ise** [comment]
@Suvraneel Actually, if anyone from the team (people who already are working on the leaderboard-backend) could work on this issue. I did not wanted to get assigned. 
Just wanted to give a suggestion to you guys, if you could take this into consideration, would be great!

**Comment by sabhisharma-ise** [comment]
@Suvraneel Okay buddy!

**Comment by monizb** [comment]
Adding to what @Suvraneel has said, this has already been handled on the frontend. People with higher number of higher point PRs are placed above other so if I have more level 3 PRs I will be placed higher than the person who has lower number of level 3 PRs

**Comment by sabhisharma-ise** [comment]
@monizb Hey, can you check the leaderboard once, it hasn't been reflected in real time!

See 👎 

![image](https://github.com/girlscript/gssoc22-leaderboard-backend/assets/100849696/c671ff25-d769-44b3-b072-096130a2e6e2)

**Comment by monizb** [comment]
Durgesh4993 has more number of level 3 PRs than you @sabhisharma-ise so he is placed higher

**Comment by sabhisharma-ise** [comment]
@monizb Ohh okay, the implementation is done is that way. It's totally fine! Thanks for clarifying.

**Comment by sabhisharma-ise** [comment]
@monizb IUpon checking the labels of PRs of @Git21221 and @sabhisharma-ise, and found out that @Git21221 is having more level3 PRs than @sabhisharma-ise . So, could you please clarify in more detail, how did came up to this conclusion of yours that it's implemented in the code?

**Comment by sabhisharma-ise** [comment]
@Suvraneel hello
I've tried to test the leaderboard locally & modified the generateLeaderboard.js file (for the changes i mentioned above)
Here is an example (it's in leaderboard.json file)

![image](https://github.com/girlscript/gssoc22-leaderboard-backend/assets/100849696/b9224b04-8d5b-4539-b534-fef2bc471385)
|*All three having score of 580, but sorted acc to their PRs, respectively*|

If you agree to the changes, we can merge this PR into the main code-base!
